
    export const items = [
  {
    id: 1,
    name: "Mario Kart 8 Deluxe",
    blurb: "High-speed chaotic racing with friends, items, and broken friendships.",
    rating: 5,
    emoji: "🏎️",
  },
  {
    id: 2,
    name: "Super Mario 3D World",
    blurb: "Leap through vibrant courses with chaotic four-player local co-op.",
    rating: 4,
    emoji: "🐱",
  },
  {
    id: 3,
    name: "Animal Crossing: New Horizons",
    blurb: "Escape to a deserted island and create your own paradise.",
    rating: 5,
    emoji: "🍃",
  },
  {
    id: 4,
    name: "The Legend of Zelda: Tears of the Kingdom",
    blurb: "Unleash your imagination by building wild inventions to explore Hyrule.",
    rating: 5,
    emoji: "🔧",
  },
  {
    id: 5,
    name: "Mortal Kombat 1",
    blurb: "Brutal fighting mechanics mixed with cinematic stories and legendary fatalities.",
    rating: 4,
    emoji: "🐉",
  },
  {
    id: 6,
    name: "Blur",
    blurb: "Real-world racing cars powered up with explosive arcade action.",
    rating: 4,
    emoji: "⚡",

    id: 7,
    name: "Minecraft",
    blurb: "Build anything you can imagine in a massive blocky sandbox.",
    rating: 5,
    emoji: "🧱",
  },

    {
    id: 8,
    name: "EA Sports FC 24",
    blurb: "The ultimate football experience featuring realistic player motion and global leagues.",
    rating: 4,
    emoji: "⚽",
  },
  {
    id: 9,
    name: "NBA 2K24",
    blurb: "Step onto the hardwood to experience authentic basketball gameplay and culture.",
    rating: 4,
    emoji: "🏀",
  },
  {
    id: 10,
    name: "Rocket League",
    blurb: "High-octane physics-based soccer played with flying, rocket-powered cars.",
    rating: 5,
    emoji: "🚗",
  },
  {
    id: 11,
    name: "Kirby and the Forgotten Land",
    blurb: "Float, inhale, and copy enemy abilities in a bright 3D platforming adventure.",
    rating: 5,
    emoji: "🎈",
  },
  {
    id: 12,
    name: "Dragon Quest XI S",
    blurb: "A massive, traditional turn-based JRPG filled with charming characters and monsters.",
    rating: 5,
    emoji: "🔮",
  },
  {
    id: 13,
    name: "Super Smash Bros. Ultimate",
    blurb: "The ultimate gaming crossover fight featuring over 80 iconic characters.",
    rating: 5,
    emoji: "🥊",
  },
  {
    id: 14,
    name: "Candy Crush Saga",
    blurb: "Switch and match colorful candies in this endlessly addictive puzzle phenomenon.",
    rating: 4,
    emoji: "🍬",
  },
  {
    id: 15,
    name: "Subway Surfers",
    blurb: "Dash and dodge oncoming trains in a colorful, fast-paced endless runner.",
    rating: 4,
    emoji: "🏃",
  },
  {
    id: 16,
    name: "Alto's Odyssey",
    blurb: "Sandboard across vast, beautiful deserts in a serene and artistic journey.",
    rating: 5,
    emoji: "🏜️",
  },
  {
    id: 17,
    name: "Bluk",
    blurb: "A minimalist, physics-based puzzle game about leaping across pillars.",
    rating: 4,
    emoji: "🟦",
  },
  {
    id: 18,
    name: "Batman: Arkham City",
    blurb: "Glide through a sprawling, dangerous mega-prison as the Dark Knight.",
    rating: 5,
    emoji: "🦇",
  },
  {
    id: 19,
    name: "Injustice 2",
    blurb: "Clash in epic fighting matches featuring powered-up DC Super Heroes and Villains.",
    rating: 4,
    emoji: "💥",
  },
  {
    id: 20,
    name: "Need for Speed Unbound",
    blurb: "Race against the clock, outsmart the police, and customize your dream street ride.",
    rating: 4,
    emoji: "🚘",
  },
  {
    id: 21,
    name: "Luigi's Mansion 3",
    blurb: "Suck up ghosts and solve puzzles in a haunted, towering hotel.",
    rating: 5,
    emoji: "👻",
  },
  {
    id: 22,
    name: "Hogwarts Legacy",
    blurb: "Experience an open-world action RPG set in the wizarding world of the 1800s.",
    rating: 5,
    emoji: "🪄",
  },
  {
    id: 23,
    name: "Resident Evil 4",
    blurb: "Survive a terrifying, action-packed nightmare in a remote European village.",
    rating: 5,
    emoji: "👁️",
  },
  {
    id: 24,
    name: "Super Mario World 2: Yoshi's Island",
    blurb: "Carry Baby Mario across beautiful, hand-drawn levels in this classic platformer.",
    rating: 5,
    emoji: "🦖",
  },
  {
    id: 25,
    name: "Mario Party Superstars",
    blurb: "Roll dice and compete in chaotic minigames on classic boards with friends.",
    rating: 4,
    emoji: "🎲",
  },
  {
    id: 26,
    name: "Final Fantasy VII Rebirth",
    blurb: "Explore a massive, gorgeous world in this epic reimagining of a RPG legend.",
    rating: 5,
    emoji: "☄️",
  },
  {
    id: 27,
    name: "Professor Layton and the Curious Village",
    blurb: "Solve charming, mind-bending puzzles to uncover the secrets of a mysterious town.",
    rating: 4,
    emoji: "🎩",
  },
  {
    id: 28,
    name: "Street Fighter 6",
    blurb: "Master an evolved fighting system and rule the streets in style.",
    rating: 5,
    emoji: "👊",
  },
  {
    id: 29,
    name: "Homescapes",
    blurb: "Solve match-three puzzles to renovate and decorate a giant family mansion.",
    rating: 3,
    emoji: "🛋️",
  },
  {
    id: 30,
    name: "Assassin's Creed Shadows",
    blurb: "Slip into feudal Japan as a stealthy shinobi or a legendary samurai.",
    rating: 4,
    emoji: "🥷",
  }

];

